const express=require('express');
const pool=require('../db');
const {validateAsset,evaluateDeck,validateTransition}=require('../domain/deckPolicy');
const router=express.Router();
const tenantOf=(req)=>String(req.user.tenant_id||req.user.organization_id||req.user.id);

router.post('/',async(req,res,next)=>{try{if(!req.body.idempotency_key||!req.body.title||!req.body.brand_version)throw new Error('idempotency_key, title, and brand_version are required');const tenant=tenantOf(req);const result=await pool.query(`INSERT INTO deck_workflows(tenant_id,owner_id,idempotency_key,title,brand_version,content)
  VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *`,[tenant,String(req.user.id),req.body.idempotency_key,req.body.title,req.body.brand_version,req.body.content||{}]);res.status(201).json(result.rows[0]);}catch(error){next(error);}});

router.post('/:id/assets',async(req,res,next)=>{try{const tenant=tenantOf(req);const asset=validateAsset(req.body);const owned=await pool.query('SELECT id FROM deck_workflows WHERE id=$1 AND tenant_id=$2',[req.params.id,tenant]);if(!owned.rows[0])return res.status(404).json({error:'Deck not found'});const result=await pool.query(`INSERT INTO deck_assets(tenant_id,workflow_id,source_ref,source_version,checksum,media_type,rights_basis,consent_ref,license_expires_at,editable_uri,metadata)
  VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[tenant,req.params.id,asset.source_ref,asset.source_version,asset.checksum,req.body.media_type||'application/octet-stream',asset.rights_basis,req.body.consent_ref||null,req.body.license_expires_at||null,req.body.editable_uri||null,asset]);res.status(201).json(result.rows[0]);}catch(error){next(error);}});

router.post('/:id/render-jobs',async(req,res,next)=>{try{const tenant=tenantOf(req);if(!req.body.provider||!req.body.format||!req.body.idempotency_key)throw new Error('provider, format, and idempotency_key are required');const owned=await pool.query('SELECT id FROM deck_workflows WHERE id=$1 AND tenant_id=$2',[req.params.id,tenant]);if(!owned.rows[0])return res.status(404).json({error:'Deck not found'});const result=await pool.query(`INSERT INTO deck_render_jobs(tenant_id,workflow_id,provider,format,idempotency_key,status,next_attempt_at)
  VALUES($1,$2,$3,$4,$5,'queued',NOW()) ON CONFLICT(tenant_id,provider,idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *`,[tenant,req.params.id,req.body.provider,req.body.format,req.body.idempotency_key]);res.status(202).json(result.rows[0]);}catch(error){next(error);}});

router.post('/:id/evaluate',async(req,res,next)=>{try{const tenant=tenantOf(req);const evaluation=evaluateDeck(req.body);const owned=await pool.query('SELECT id FROM deck_workflows WHERE id=$1 AND tenant_id=$2',[req.params.id,tenant]);if(!owned.rows[0])return res.status(404).json({error:'Deck not found'});await pool.query(`INSERT INTO deck_evaluations(tenant_id,workflow_id,fixture_version,overflow_count,contrast_score,accessibility_score,brand_score,export_valid,passed,details)
  VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[tenant,req.params.id,req.body.fixture_version||'unversioned',Number(req.body.overflow_count||0),Number(req.body.contrast_score||0),Number(req.body.accessibility),Number(req.body.brand_compliance),Number(req.body.export_compatibility)>=.95,!evaluation.blocked,{...req.body,evaluation}]);res.json(evaluation);}catch(error){next(error);}});

router.post('/:id/transition',async(req,res,next)=>{const client=await pool.connect();try{const tenant=tenantOf(req);await client.query('BEGIN');const found=await client.query('SELECT * FROM deck_workflows WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[req.params.id,tenant]);const current=found.rows[0];if(!current){await client.query('ROLLBACK');return res.status(404).json({error:'Deck not found'});}if(Number(req.body.version)!==current.version){await client.query('ROLLBACK');return res.status(409).json({error:'Stale workflow version'});}const assetCount=Number((await client.query('SELECT COUNT(*) FROM deck_assets WHERE workflow_id=$1 AND tenant_id=$2',[current.id,tenant])).rows[0].count);const latest=await client.query('SELECT passed FROM deck_evaluations WHERE workflow_id=$1 AND tenant_id=$2 ORDER BY evaluated_at DESC LIMIT 1',[current.id,tenant]);validateTransition(current.stage,req.body.to_stage,{...req.body.context,role:req.user.role||'viewer',actorId:String(req.user.id),createdBy:current.owner_id,assetCount,evaluationBlocked:latest.rows[0]?!latest.rows[0].passed:true});const result=await client.query('UPDATE deck_workflows SET stage=$1,version=version+1,updated_at=NOW() WHERE id=$2 RETURNING *',[req.body.to_stage,current.id]);await client.query('INSERT INTO deck_workflow_audit(tenant_id,workflow_id,actor_id,action,from_stage,to_stage,payload) VALUES($1,$2,$3,$4,$5,$6,$7)',[tenant,current.id,String(req.user.id),'deck.transitioned',current.stage,req.body.to_stage,req.body.context||{}]);await client.query('COMMIT');res.json(result.rows[0]);}catch(error){await client.query('ROLLBACK').catch(()=>{});next(error);}finally{client.release();}});
module.exports=router;
